# Generated by Django 4.2.16 on 2026-01-05 02:39

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemCategory",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("published", models.BooleanField(default=False)),
                ("icon_id", models.IntegerField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ItemGroup",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("anchorable", models.BooleanField(default=False)),
                ("anchored", models.BooleanField(default=False)),
                ("fittable_non_singleton", models.BooleanField(default=False)),
                ("icon_id", models.IntegerField(blank=True, default=None, null=True)),
                ("published", models.BooleanField(default=False)),
                ("use_base_price", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemcategory",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ItemType",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("name_en", models.CharField(max_length=250, null=True)),
                ("name_de", models.CharField(max_length=250, null=True)),
                ("name_es", models.CharField(max_length=250, null=True)),
                ("name_it_it", models.CharField(max_length=250, null=True)),
                ("name_ja", models.CharField(max_length=250, null=True)),
                ("name_ko_kr", models.CharField(max_length=250, null=True)),
                ("name_fr_fr", models.CharField(max_length=250, null=True)),
                ("name_nl_nl", models.CharField(max_length=250, null=True)),
                ("name_pl_pl", models.CharField(max_length=250, null=True)),
                ("name_ru", models.CharField(max_length=250, null=True)),
                ("name_uk", models.CharField(max_length=250, null=True)),
                ("name_zh_hans", models.CharField(max_length=250, null=True)),
                ("base_price", models.FloatField(blank=True, default=None, null=True)),
                ("capacity", models.FloatField(blank=True, default=None, null=True)),
                ("description", models.TextField()),
                ("description_en", models.TextField(null=True)),
                ("description_de", models.TextField(null=True)),
                ("description_es", models.TextField(null=True)),
                ("description_it_it", models.TextField(null=True)),
                ("description_ja", models.TextField(null=True)),
                ("description_ko_kr", models.TextField(null=True)),
                ("description_fr_fr", models.TextField(null=True)),
                ("description_nl_nl", models.TextField(null=True)),
                ("description_pl_pl", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("description_uk", models.TextField(null=True)),
                ("description_zh_hans", models.TextField(null=True)),
                (
                    "faction_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "graphic_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("icon_id", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "market_group_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("mass", models.FloatField(blank=True, default=None, null=True)),
                (
                    "meta_group_id_raw",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "portion_size",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("published", models.BooleanField(default=False)),
                ("race_id", models.IntegerField(blank=True, default=None, null=True)),
                ("radius", models.FloatField(blank=True, default=None, null=True)),
                ("sound_id", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "variation_parent_type_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                ("volume", models.FloatField(blank=True, default=None, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
