# Generated by Django 4.2.16 on 2026-03-01 03:25

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0014_dogmaeffect_description_de_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlueprintActivityMaterial",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "activity_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "eve_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_activity_materials",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "material_eve_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["eve_type", "activity_id"],
                        name="esde_bam_evact_idx",
                    ),
                    models.Index(
                        fields=["material_eve_type", "activity_id"],
                        name="esde_bam_mtact_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BlueprintActivityProduct",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_id",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "activity_name",
                    models.CharField(
                        blank=True, default=None, max_length=50, null=True
                    ),
                ),
                ("quantity", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "probability",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "eve_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_activity_products",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "product_eve_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["eve_type", "activity_id"],
                        name="esde_bap_evact_idx",
                    ),
                    models.Index(
                        fields=["product_eve_type", "activity_id"],
                        name="esde_bap_pract_idx",
                    ),
                ],
            },
        ),
    ]
