# Generated by Django 5.2.16 on 2026-07-30 14:54

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0021_archetype_freelancejobschema_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SovereigntyUpgrade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hourly_upkeep",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "startup_cost",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "power_production",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "power_allocation",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "workforce_production",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "workforce_allocation",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "mutually_exclusive_group",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "fuel_item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sovereignty_upgrade_fuel",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "item_type",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sovereignty_upgrade",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
