# Generated by Django 5.2.12 on 2026-08-11 12:24

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0024_notificationtype"),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporationRole",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("name_en", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_de", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_es", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_it_it",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ja", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_ko_kr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_fr_fr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_nl_nl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_pl_pl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ru", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_uk", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_zh_hans",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "description_en",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_it_it",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ja",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ko_kr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_fr_fr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_nl_nl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_pl_pl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_zh_hans",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CorporationRoleGroup",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("name_en", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_de", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_es", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_it_it",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ja", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_ko_kr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_fr_fr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_nl_nl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_pl_pl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ru", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_uk", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_zh_hans",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "applies_to",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                (
                    "applies_to_grantable",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("is_divisional", models.BooleanField(default=False)),
                ("is_locational", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CorporationRoleGroupMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corporation_role",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_groups",
                        to="eve_sde.corporationrole",
                    ),
                ),
                (
                    "role_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.corporationrolegroup",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
