# Generated by Django 5.2.12 on 2026-08-11 12:36

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0026_landmark"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetenoxMoonDrill",
            fields=[
                (
                    "item_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="metenox_moon_drill",
                        serialize=False,
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "mining_cycle_time",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "mining_efficiency",
                    models.FloatField(blank=True, default=None, null=True),
                ),
                (
                    "reagents_consumed_per_cycle",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
