# Generated by Django 5.2.12 on 2026-08-11 13:02

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0028_skillplan_skillplanmilestone_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeList",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_es",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_it_it",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_ja",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_ko_kr",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_fr_fr",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_nl_nl",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_pl_pl",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_uk",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "name_zh_hans",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default=None,
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "internal_name",
                    models.CharField(
                        blank=True, default=None, max_length=250, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "description_en",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_it_it",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ja",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ko_kr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_fr_fr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_nl_nl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_pl_pl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_zh_hans",
                    models.TextField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TypeListCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excluded", models.BooleanField(default=False)),
                (
                    "item_category",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemcategory",
                    ),
                ),
                (
                    "type_list",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="eve_sde.typelist",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TypeListGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excluded", models.BooleanField(default=False)),
                (
                    "item_group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemgroup",
                    ),
                ),
                (
                    "type_list",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="groups",
                        to="eve_sde.typelist",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="TypeListType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("excluded", models.BooleanField(default=False)),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "type_list",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="eve_sde.typelist",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
