# Generated by Django 5.2.15 on 2026-08-14 05:08

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0029_typelist_typelistcategory_typelistgroup_typelisttype"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemtype",
            name="is_dynamic_type",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="itemtype",
            name="is_repackable",
            field=models.BooleanField(default=False),
        ),
    ]
