# Generated by Django 5.2.16 on 2026-08-09 12:19

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0030_itemtype_is_dynamic_type_itemtype_is_repackable"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanetResource",
            fields=[
                (
                    "planet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="resource",
                        serialize=False,
                        to="eve_sde.planet",
                    ),
                ),
                ("power", models.IntegerField(blank=True, default=None, null=True)),
                ("workforce", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "reagent_amount_per_cycle",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_cycle_period",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_secured_capacity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_unsecured_capacity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
