# Generated by Django 5.2.15 on 2026-08-16 04:38

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0031_planetresource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Star",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=250)),
                ("x", models.FloatField(blank=True, default=None, null=True)),
                ("y", models.FloatField(blank=True, default=None, null=True)),
                ("z", models.FloatField(blank=True, default=None, null=True)),
                ("age", models.FloatField(blank=True, default=None, null=True)),
                ("life", models.FloatField(blank=True, default=None, null=True)),
                ("luminosity", models.FloatField(blank=True, default=None, null=True)),
                ("radius", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "spectral_class",
                    models.CharField(
                        blank=True, default=None, max_length=10, null=True
                    ),
                ),
                ("temperature", models.FloatField(blank=True, default=None, null=True)),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "solar_system",
                    models.OneToOneField(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="star",
                        to="eve_sde.solarsystem",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="StarResource",
            fields=[
                (
                    "star",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="resource",
                        serialize=False,
                        to="eve_sde.star",
                    ),
                ),
                ("power", models.IntegerField(blank=True, default=None, null=True)),
                ("workforce", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "reagent_amount_per_cycle",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_cycle_period",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_secured_capacity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_unsecured_capacity",
                    models.IntegerField(blank=True, default=None, null=True),
                ),
                (
                    "reagent_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
    ]
