# Generated by Django 5.2.15 on 2026-08-16 04:44

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0032_star_starresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarsystem",
            name="star_id_raw",
        ),
    ]
