# Generated by Django 5.2.17 on 2026-08-16 05:59

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0033_remove_solarsystem_star_id_raw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="typelist",
            name="internal_name",
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
