# Generated by Django 5.2.17 on 2026-08-16 06:11

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0034_alter_typelist_internal_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="star",
            name="radius",
            field=models.BigIntegerField(blank=True, default=None, null=True),
        ),
    ]
