# Generated by Django 5.2.12 on 2026-08-17 13:10

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0035_alter_star_radius"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="star",
            name="name",
        ),
    ]
