# Generated by Django 5.2.12 on 2026-10-06 12:35

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0036_remove_star_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(db_index=True, max_length=250)),
                ("name_en", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_de", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_es", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_it_it",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ja", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_ko_kr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_fr_fr",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_nl_nl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                (
                    "name_pl_pl",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("name_ru", models.CharField(db_index=True, max_length=250, null=True)),
                ("name_uk", models.CharField(db_index=True, max_length=250, null=True)),
                (
                    "name_zh_hans",
                    models.CharField(db_index=True, max_length=250, null=True),
                ),
                ("description", models.TextField(blank=True, default=None, null=True)),
                (
                    "description_en",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_it_it",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ja",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ko_kr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_fr_fr",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_nl_nl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_pl_pl",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_uk",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "description_zh_hans",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="eve_sde.itemgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="CertificateRecommendedType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_types",
                        to="eve_sde.certificate",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommended_certificates",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("certificate", "item_type"),
                        name="esde_certificaterecommendedtype_nk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CertificateSkill",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic", models.IntegerField(blank=True, default=None, null=True)),
                ("standard", models.IntegerField(blank=True, default=None, null=True)),
                ("improved", models.IntegerField(blank=True, default=None, null=True)),
                ("advanced", models.IntegerField(blank=True, default=None, null=True)),
                ("elite", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="eve_sde.certificate",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("certificate", "item_type"),
                        name="esde_certificateskill_nk",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Mastery",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="eve_sde.certificate",
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="masteries",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("item_type", "level", "certificate"),
                        name="esde_mastery_nk",
                    )
                ],
            },
        ),
    ]
