# Generated by Django 5.2.12 on 2026-10-06 12:52

# Django
from django.db import migrations, models

# Natural keys of the models getting a unique constraint below. These tables
# used to be wiped and reloaded every import, so they can hold duplicates
# that the SDE itself contains (e.g. a type listed twice in a type list).
NATURAL_KEYS = {
    "blueprintactivitymaterial": ("blueprint_activity_id", "item_type_id"),
    "blueprintactivityproduct": ("blueprint_activity_id", "item_type_id"),
    "corporationrolegroupmembership": ("corporation_role_id", "role_group_id"),
    "itemtypematerials": ("item_type_id", "material_item_type_id"),
    "skillplanmilestone": ("skill_plan_id", "item_type_id"),
    "skillplanskillrequirement": ("skill_plan_id", "item_type_id", "level"),
    "typedogma": ("item_type_id", "dogma_attribute_id"),
    "typeeffect": ("item_type_id", "dogma_effect_id"),
    "typelistcategory": ("type_list_id", "item_category_id", "excluded"),
    "typelistgroup": ("type_list_id", "item_group_id", "excluded"),
    "typelisttype": ("type_list_id", "item_type_id", "excluded"),
}


def remove_duplicates(apps, schema_editor):
    """Keep the lowest pk for each natural key so the constraints can be added."""
    for model_name, fields in NATURAL_KEYS.items():
        model = apps.get_model("eve_sde", model_name)
        seen = set()
        duplicates = []
        for row in model.objects.order_by("pk").values_list(*fields, "pk").iterator():
            key = row[:-1]
            if None in key:
                # NULLs never clash in a unique constraint
                continue
            if key in seen:
                duplicates.append(row[-1])
            else:
                seen.add(key)
        for i in range(0, len(duplicates), 1000):
            model.objects.filter(pk__in=duplicates[i:i + 1000]).delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "eve_sde",
            "0037_certificate_certificaterecommendedtype_certificateskill_mastery",
        ),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="blueprintactivitymaterial",
            constraint=models.UniqueConstraint(
                fields=("blueprint_activity", "item_type"),
                name="esde_blueprintactivitymaterial_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="blueprintactivityproduct",
            constraint=models.UniqueConstraint(
                fields=("blueprint_activity", "item_type"),
                name="esde_blueprintactivityproduct_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="corporationrolegroupmembership",
            constraint=models.UniqueConstraint(
                fields=("corporation_role", "role_group"),
                name="esde_corporationrolegroupmembership_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="itemtypematerials",
            constraint=models.UniqueConstraint(
                fields=("item_type", "material_item_type"),
                name="esde_itemtypematerials_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="skillplanmilestone",
            constraint=models.UniqueConstraint(
                fields=("skill_plan", "item_type"), name="esde_skillplanmilestone_nk"
            ),
        ),
        migrations.AddConstraint(
            model_name="skillplanskillrequirement",
            constraint=models.UniqueConstraint(
                fields=("skill_plan", "item_type", "level"),
                name="esde_skillplanskillrequirement_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="typedogma",
            constraint=models.UniqueConstraint(
                fields=("item_type", "dogma_attribute"), name="esde_typedogma_nk"
            ),
        ),
        migrations.AddConstraint(
            model_name="typeeffect",
            constraint=models.UniqueConstraint(
                fields=("item_type", "dogma_effect"), name="esde_typeeffect_nk"
            ),
        ),
        migrations.AddConstraint(
            model_name="typelistcategory",
            constraint=models.UniqueConstraint(
                fields=("type_list", "item_category", "excluded"),
                name="esde_typelistcategory_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="typelistgroup",
            constraint=models.UniqueConstraint(
                fields=("type_list", "item_group", "excluded"),
                name="esde_typelistgroup_nk",
            ),
        ),
        migrations.AddConstraint(
            model_name="typelisttype",
            constraint=models.UniqueConstraint(
                fields=("type_list", "item_type", "excluded"),
                name="esde_typelisttype_nk",
            ),
        ),
    ]
