# Generated by Django 5.2.12 on 2026-10-07 09:36

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0038_natural_key_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="evesdesection",
            name="import_fingerprint",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
