# Generated by Django 5.2.12 on 2026-10-08 10:46

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eve_sde", "0039_eve_sde_section_import_fingerprint"),
    ]

    operations = [
        migrations.AddField(
            model_name="evesdesection",
            name="removed_pks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
