[build-system]
build-backend = "hatchling.build"
requires = [
    "hatchling",
]

[project]
name = "django-eveonline-sde"
description = "Eve Online SDE Export in Django Model form"
readme = "README.md"
keywords = [
    "allianceauth",
    "eve online",
]
license = { file = "LICENSE" }
authors = [
    { name = "Aaron Kable", email = "aaronkable@gmail.com" },
]
requires-python = ">=3.10,<3.15"
classifiers = [
    "Environment :: Web Environment",
    "Framework :: Django",
    "Framework :: Django :: 4.2",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Internet :: WWW/HTTP :: Dynamic Content",
]
dynamic = [
    "version",
]
dependencies = [
    "celery>=5,<6",
    "celery-once>=3,<4",
    "django-modeltranslation==0.19.17",
    "django-solo>=2,<3",
    "httpx>=0.28,<1",
]
urls."Issue / Bug Reports" = "https://github.com/Solar-Helix-Independent-Transport/django-eveonline-sde/issues"
urls.Changelog = "https://github.com/Solar-Helix-Independent-Transport/django-eveonline-sde/releases"

[tool.hatch]
version.path = "eve_sde/__init__.py"
build.include = [
    "eve_sde",
]

[tool.autopep8]
ignore = [ "E203", "E231", "E501", "W291", "W293", "W503" ]
select = [ "B", "B950", "C", "E", "F", "W" ]
exclude = ".git,*migrations*,.tox,dist,htmlcov"
max-line-length = 120

[tool.isort]
profile = "black"
multi_line_output = 3
sections = [
    "FUTURE",
    "STDLIB",
    "THIRDPARTY",
    "DJANGO",
    "ALLIANCEAUTH",
    "FIRSTPARTY",
    "LOCALFOLDER",
]
skip_gitignore = true
import_heading_stdlib = "Standard Library"
import_heading_thirdparty = "Third Party"
import_heading_firstparty = "Django EVE SDE"
import_heading_allianceauth = "Alliance Auth"
import_heading_django = "Django"
known_allianceauth = [ "allianceauth", "esi" ]
known_django = [ "django" ]

[tool.flake8]
exclude = [ ".git", "*migrations*", ".tox", "dist", "htmlcov" ]
max-line-length = 120
select = [ "C", "E", "F", "W", "B", "B950" ]
ignore = [ "E203", "E231", "E501", "W503", "W291", "W293" ]
